name: Test-Mac
on: push
jobs:
  deploy:
    name: Test MacOs Binary
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Setup NPM 
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1 
        with:
          dotnet-version: '5.0.x' # SDK Version to use

      - name: Install Electron Tooling
        run: dotnet tool install ElectronNET.CLI -g

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build x64 Binary
        run: electronize build /target osx
      - name: Check Binaries
        run: ls bin/Desktop/
      - name: Rename x64 Binary
        run: mv "bin/Desktop/RpgNotes.Desktop" "bin/Desktop/RpgNotes.Mac.x64"