name: Test-Linux
on: push
jobs:
  deploy:
    name: Test Linux Binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Setup NPM 
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1 
        with:
          dotnet-version: '5.0.x' # SDK Version to use

      - name: Install Electron Tooling
        env: 
          GITHUB_USERNAME: qkmaxware
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet tool install ElectronNET.CLI -g

      - name: Restore Dependencies
        env: 
          GITHUB_USERNAME: qkmaxware
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet restore

      - name: Build x64 Binary
        env: 
          GITHUB_USERNAME: qkmaxware
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: electronize build /target linux

      - name: Check Binaries
        run: ls bin/Desktop/

      - name: Rename x64 Binary
        run: mv "bin/Desktop/RpgNotes.Desktop-1.0.0.AppImage" "bin/Desktop/RpgNotes.Linux.x64.AppImage"